// Code generated by go generate; DO NOT EDIT.

package proxyconf

const (
	GeneratedUpstreamTag   = "2.1.18"
	GeneratedExampleSHA256 = "f16ce4b8e18ab5f8359d2caedffbcd1b5b23d6f7cd49d50704e67e5f80821536"
)
