//go:build ignore

package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	tomlPath := filepath.Join(root, "upstream", "example-dnscrypt-proxy.toml")
	verPath := filepath.Join(root, "upstream", "VERSION")
	b, err := os.ReadFile(tomlPath)
	if err != nil {
		fatal(err)
	}
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	tag, err := os.ReadFile(verPath)
	if err != nil {
		fatal(err)
	}
	sum := sha256.Sum256(b)
	hexSum := hex.EncodeToString(sum[:])
	src := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage proxyconf\n\nconst (\n\tGeneratedUpstreamTag   = %q\n\tGeneratedExampleSHA256 = %q\n)\n",
		strings.TrimSpace(string(tag)), hexSum)
	out := filepath.Join(root, "catalog_gen.go")
	if err := os.WriteFile(out, []byte(src), 0o644); err != nil {
		fatal(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%s %s)\n", out, strings.TrimSpace(string(tag)), hexSum)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
